# Generated by Django 4.0.6 on 2022-07-14 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Documnent',
            new_name='Document',
        ),
    ]
